version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5001:5000"
    depends_on:
      - backend